version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ./gradlew clean build
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: root
      POSTGRES_DB: hr_automation
    ports:
      - "5432:5432"
    restart: always