version: '3.0'

services:
  main:
    image: 'hr-automation:latest'
    container_name: main
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/hr_automation
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - AWS_ACCESS_KEY_ID=YCAJEt4WD4PxPGAqxKcXlEyY-
      - AWS_SECRET_ACCESS_KEY=YCNPyDN7Vb45pd5mTk5uTCjq1p6k2TKtG8NJS5zB
    restart: always

  postgres:
    container_name: postgres
    image: postgres:12
    build:
      context: ./
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: hr_automation
    restart: always